import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header/header';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { ClerkProvider } from '@clerk/nextjs';
import { ConvexClientProvider } from './convex-client-provider';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
            <ConvexClientProvider>
              <AppSidebar />
              <main className="flex-1 flex flex-col min-h-screen">
                <Header />
                <div className="flex">
                  <div className="flex flex-1">
                    <div className="w-full">{children}</div>
                    <div className="hidden xl:block w-96 sticky top-20 h-[calc(100vh-5rem)]">
                      <div className="flex justify-center items-center p-4">
                        right menu
                      </div>
                    </div>
                  </div>
                </div>
              </main>
              <Toaster richColors />
            </ConvexClientProvider>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
