export const top25Cities = [
  {
    city: 'Austin',
    state: 'Texas',
    value: 'austin',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
  },
  {
    city: 'Charlotte',
    state: 'North Carolina',
    value: 'charlotte',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_North_Carolina.svg',
  },
  {
    city: 'Chicago',
    state: 'Illinois',
    value: 'chicago',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Illinois.svg',
  },
  {
    city: 'Columbus',
    state: 'Ohio',
    value: 'columbus',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg',
  },
  {
    city: 'Dallas',
    state: 'Texas',
    value: 'dallas',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
  },
  {
    city: 'Denver',
    state: 'Colorado',
    value: 'denver',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg',
  },
  {
    city: 'El Paso',
    state: 'Texas',
    value: 'el-paso',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
  },
  {
    city: 'Fort Worth',
    state: 'Texas',
    value: 'fort-worth',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
  },
  {
    city: 'Houston',
    state: 'Texas',
    value: 'houston',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
  },
  {
    city: 'Indianapolis',
    state: 'Indiana',
    value: 'indianapolis',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Indiana.svg',
  },
  {
    city: 'Jacksonville',
    state: 'Florida',
    value: 'jacksonville',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg',
  },
  {
    city: 'Las Vegas',
    state: 'Nevada',
    value: 'las-vegas',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg',
  },
  {
    city: 'Los Angeles',
    state: 'California',
    value: 'los-angeles',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg',
  },
  {
    city: 'Louisville',
    state: 'Kentucky',
    value: 'louisville',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Flag_of_Kentucky.svg',
  },
  {
    city: 'Memphis',
    state: 'Tennessee',
    value: 'memphis',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg',
  },
  {
    city: 'Milwaukee',
    state: 'Wisconsin',
    value: 'milwaukee',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Wisconsin.svg',
  },
  {
    city: 'Nashville',
    state: 'Tennessee',
    value: 'nashville',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg',
  },
  {
    city: 'New York',
    state: 'New York',
    value: 'new-york',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_New_York.svg',
  },
  {
    city: 'Oklahoma City',
    state: 'Oklahoma',
    value: 'oklahoma-city',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Oklahoma.svg',
  },
  {
    city: 'Philadelphia',
    state: 'Pennsylvania',
    value: 'philadelphia',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Pennsylvania.svg',
  },
  {
    city: 'Phoenix',
    state: 'Arizona',
    value: 'phoenix',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg',
  },
  {
    city: 'San Antonio',
    state: 'Texas',
    value: 'san-antonio',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg',
  },
  {
    city: 'San Diego',
    state: 'California',
    value: 'san-diego',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg',
  },
  {
    city: 'San Jose',
    state: 'California',
    value: 'san-jose',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg',
  },
  {
    city: 'Washington',
    state: 'D.C.',
    value: 'washington',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Washington%2C_D.C.svg/250px-Flag_of_Washington%2C_D.C.svg.png',
  },
];
